namespace Gfx;

public static class VulkanDynamicStateExtensions
{
	public static Silk.NET.Vulkan.DynamicState ToVulkan(DynamicState state)
	{
		return state switch
		{
			DynamicState.Viewport                            => Silk.NET.Vulkan.DynamicState.Viewport                           ,
			DynamicState.Scissor                             => Silk.NET.Vulkan.DynamicState.Scissor                            ,
			DynamicState.LineWidth                           => Silk.NET.Vulkan.DynamicState.LineWidth                          ,
			DynamicState.DepthBias                           => Silk.NET.Vulkan.DynamicState.DepthBias                          ,
			DynamicState.BlendConstants                      => Silk.NET.Vulkan.DynamicState.BlendConstants                     ,
			DynamicState.DepthBounds                         => Silk.NET.Vulkan.DynamicState.DepthBounds                        ,
			DynamicState.StencilCompareMask                  => Silk.NET.Vulkan.DynamicState.StencilCompareMask                 ,
			DynamicState.StencilWriteMask                    => Silk.NET.Vulkan.DynamicState.StencilWriteMask                   ,
			DynamicState.StencilReference                    => Silk.NET.Vulkan.DynamicState.StencilReference                   ,
			DynamicState.ViewportWScalingNV                  => Silk.NET.Vulkan.DynamicState.ViewportWScalingNV                 ,
			DynamicState.DiscardRectangleExt                 => Silk.NET.Vulkan.DynamicState.DiscardRectangleExt                ,
			DynamicState.DiscardRectangleEnableExt           => Silk.NET.Vulkan.DynamicState.DiscardRectangleEnableExt          ,
			DynamicState.DiscardRectangleModeExt             => Silk.NET.Vulkan.DynamicState.DiscardRectangleModeExt            ,
			DynamicState.SampleLocationsExt                  => Silk.NET.Vulkan.DynamicState.SampleLocationsExt                 ,
			DynamicState.ViewportShadingRatePaletteNV        => Silk.NET.Vulkan.DynamicState.ViewportShadingRatePaletteNV       ,
			DynamicState.ViewportCoarseSampleOrderNV         => Silk.NET.Vulkan.DynamicState.ViewportCoarseSampleOrderNV        ,
			DynamicState.ExclusiveScissorEnableNV            => Silk.NET.Vulkan.DynamicState.ExclusiveScissorEnableNV           ,
			DynamicState.ExclusiveScissorNV                  => Silk.NET.Vulkan.DynamicState.ExclusiveScissorNV                 ,
			DynamicState.FragmentShadingRateKhr              => Silk.NET.Vulkan.DynamicState.FragmentShadingRateKhr             ,
			DynamicState.LineStippleExt                      => Silk.NET.Vulkan.DynamicState.LineStippleExt                     ,
			DynamicState.CullMode                            => Silk.NET.Vulkan.DynamicState.CullMode                           ,
			DynamicState.FrontFace                           => Silk.NET.Vulkan.DynamicState.FrontFace                          ,
			DynamicState.PrimitiveTopology                   => Silk.NET.Vulkan.DynamicState.PrimitiveTopology                  ,
			DynamicState.ViewportWithCount                   => Silk.NET.Vulkan.DynamicState.ViewportWithCount                  ,
			DynamicState.ScissorWithCount                    => Silk.NET.Vulkan.DynamicState.ScissorWithCount                   ,
			DynamicState.VertexInputBindingStride            => Silk.NET.Vulkan.DynamicState.VertexInputBindingStride           ,
			DynamicState.DepthTestEnable                     => Silk.NET.Vulkan.DynamicState.DepthTestEnable                    ,
			DynamicState.DepthWriteEnable                    => Silk.NET.Vulkan.DynamicState.DepthWriteEnable                   ,
			DynamicState.DepthCompareOp                      => Silk.NET.Vulkan.DynamicState.DepthCompareOp                     ,
			DynamicState.DepthBoundsTestEnable               => Silk.NET.Vulkan.DynamicState.DepthBoundsTestEnable              ,
			DynamicState.StencilTestEnable                   => Silk.NET.Vulkan.DynamicState.StencilTestEnable                  ,
			DynamicState.StencilOp                           => Silk.NET.Vulkan.DynamicState.StencilOp                          ,
			DynamicState.RayTracingPipelineStackSizeKhr      => Silk.NET.Vulkan.DynamicState.RayTracingPipelineStackSizeKhr     ,
			DynamicState.VertexInputExt                      => Silk.NET.Vulkan.DynamicState.VertexInputExt                     ,
			DynamicState.PatchControlPointsExt               => Silk.NET.Vulkan.DynamicState.PatchControlPointsExt              ,
			DynamicState.RasterizerDiscardEnable             => Silk.NET.Vulkan.DynamicState.RasterizerDiscardEnable            ,
			DynamicState.DepthBiasEnable                     => Silk.NET.Vulkan.DynamicState.DepthBiasEnable                    ,
			DynamicState.LogicOpExt                          => Silk.NET.Vulkan.DynamicState.LogicOpExt                         ,
			DynamicState.PrimitiveRestartEnable              => Silk.NET.Vulkan.DynamicState.PrimitiveRestartEnable             ,
			DynamicState.ColorWriteEnableExt                 => Silk.NET.Vulkan.DynamicState.ColorWriteEnableExt                ,
			DynamicState.TessellationDomainOriginExt         => Silk.NET.Vulkan.DynamicState.TessellationDomainOriginExt        ,
			DynamicState.DepthClampEnableExt                 => Silk.NET.Vulkan.DynamicState.DepthClampEnableExt                ,
			DynamicState.PolygonModeExt                      => Silk.NET.Vulkan.DynamicState.PolygonModeExt                     ,
			DynamicState.RasterizationSamplesExt             => Silk.NET.Vulkan.DynamicState.RasterizationSamplesExt            ,
			DynamicState.SampleMaskExt                       => Silk.NET.Vulkan.DynamicState.SampleMaskExt                      ,
			DynamicState.AlphaToCoverageEnableExt            => Silk.NET.Vulkan.DynamicState.AlphaToCoverageEnableExt           ,
			DynamicState.AlphaToOneEnableExt                 => Silk.NET.Vulkan.DynamicState.AlphaToOneEnableExt                ,
			DynamicState.LogicOpEnableExt                    => Silk.NET.Vulkan.DynamicState.LogicOpEnableExt                   ,
			DynamicState.ColorBlendEnableExt                 => Silk.NET.Vulkan.DynamicState.ColorBlendEnableExt                ,
			DynamicState.ColorBlendEquationExt               => Silk.NET.Vulkan.DynamicState.ColorBlendEquationExt              ,
			DynamicState.ColorWriteMaskExt                   => Silk.NET.Vulkan.DynamicState.ColorWriteMaskExt                  ,
			DynamicState.RasterizationStreamExt              => Silk.NET.Vulkan.DynamicState.RasterizationStreamExt             ,
			DynamicState.ConservativeRasterizationModeExt    => Silk.NET.Vulkan.DynamicState.ConservativeRasterizationModeExt   ,
			DynamicState.ExtraPrimitiveOverestimationSizeExt => Silk.NET.Vulkan.DynamicState.ExtraPrimitiveOverestimationSizeExt,
			DynamicState.DepthClipEnableExt                  => Silk.NET.Vulkan.DynamicState.DepthClipEnableExt                 ,
			DynamicState.SampleLocationsEnableExt            => Silk.NET.Vulkan.DynamicState.SampleLocationsEnableExt           ,
			DynamicState.ColorBlendAdvancedExt               => Silk.NET.Vulkan.DynamicState.ColorBlendAdvancedExt              ,
			DynamicState.ProvokingVertexModeExt              => Silk.NET.Vulkan.DynamicState.ProvokingVertexModeExt             ,
			DynamicState.LineRasterizationModeExt            => Silk.NET.Vulkan.DynamicState.LineRasterizationModeExt           ,
			DynamicState.LineStippleEnableExt                => Silk.NET.Vulkan.DynamicState.LineStippleEnableExt               ,
			DynamicState.DepthClipNegativeOneToOneExt        => Silk.NET.Vulkan.DynamicState.DepthClipNegativeOneToOneExt       ,
			DynamicState.ViewportWScalingEnableNV            => Silk.NET.Vulkan.DynamicState.ViewportWScalingEnableNV           ,
			DynamicState.ViewportSwizzleNV                   => Silk.NET.Vulkan.DynamicState.ViewportSwizzleNV                  ,
			DynamicState.CoverageToColorEnableNV             => Silk.NET.Vulkan.DynamicState.CoverageToColorEnableNV            ,
			DynamicState.CoverageToColorLocationNV           => Silk.NET.Vulkan.DynamicState.CoverageToColorLocationNV          ,
			DynamicState.CoverageModulationModeNV            => Silk.NET.Vulkan.DynamicState.CoverageModulationModeNV           ,
			DynamicState.CoverageModulationTableEnableNV     => Silk.NET.Vulkan.DynamicState.CoverageModulationTableEnableNV    ,
			DynamicState.CoverageModulationTableNV           => Silk.NET.Vulkan.DynamicState.CoverageModulationTableNV          ,
			DynamicState.ShadingRateImageEnableNV            => Silk.NET.Vulkan.DynamicState.ShadingRateImageEnableNV           ,
			DynamicState.RepresentativeFragmentTestEnableNV  => Silk.NET.Vulkan.DynamicState.RepresentativeFragmentTestEnableNV ,
			DynamicState.CoverageReductionModeNV             => Silk.NET.Vulkan.DynamicState.CoverageReductionModeNV            ,
			DynamicState.AttachmentFeedbackLoopEnableExt     => Silk.NET.Vulkan.DynamicState.AttachmentFeedbackLoopEnableExt    ,
			_                                                => throw new ArgumentOutOfRangeException(nameof(state), state, null)
		};
	}
}