namespace Gfx;

[Flags]
public enum DeviceBufferUsage
{
	TransferSrc                                = 1 <<0,
	TransferDst                                = 1 <<1,
	UniformTexelBuffer                         = 1 <<2,
	StorageTexelBuffer                         = 1 <<3,
	UniformBuffer                              = 1 <<4,
	StorageBuffer                              = 1 <<5,
	IndexBuffer                                = 1 <<6,
	VertexBuffer                               = 1 <<7,
	IndirectBuffer                             = 1 <<8,
	VideoDecodeSrcKhr                          = 1 <<9,
	VideoDecodeDstKhr                          = 1 <<10,
	TransformFeedbackBufferExt                 = 1 <<11,
	TransformFeedbackCounterBufferExt          = 1 <<12,
	ConditionalRenderingExt                    = 1 <<13,
	ExecutionGraphScratchAmdx                  = 1 <<14,
	AccelerationStructureBuildInputReadOnlyKhr = 1 <<15,
	AccelerationStructureStorageKhr            = 1 <<16,
	ShaderBindingTableKhr                      = 1 <<17,
	RayTracingNV                               = 1 <<18,
	ShaderDeviceAddressExt                     = 1 <<19,
	ShaderDeviceAddressKhr                     = 1 <<20,
	VideoEncodeDstKhr                          = 1 <<21,
	VideoEncodeSrcKhr                          = 1 <<22,
	SamplerDescriptorBufferExt                 = 1 <<23,
	ResourceDescriptorBufferExt                = 1 <<24,
	PushDescriptorsDescriptorBufferExt         = 1 <<25,
	MicromapBuildInputReadOnlyExt              = 1 <<26,
	MicromapStorageExt                         = 1 <<27,
	ShaderDeviceAddress                        = 1 <<28,
}